- name: Verify
  hosts: all

  tasks:
  - name: Check yq version
    command: "yq --version"
    ignore_errors: yes
    register: yq_current_version

  - name: Ensure yq is the correct version
    assert:
      that:
        - "'4.20.1' in yq_current_version.stdout"